apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prov
  namespace: kube-system
spec:
  replicas: 1
  strategy:
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  template:
    metadata:
      labels:
        run: prov
    spec:
      tolerations:
      - key: "dedicated"
        value: "master"
        effect: "NoSchedule"
      nodeSelector:
        kubeadm.alpha.kubernetes.io/role: master
      containers:
      - name: git-sync
        image: git-sync:version
        imagePullPolicy: Always
        volumeMounts:
        - name: markdown
          mountPath: /git

        - name: secr
          mountPath: /root/.ssh

        env:
        - name: GIT_REPO_HOSTNAME
          value:
        - name: GIT_SYNC_REPO
          value: repo.git
        - name: GIT_SYNC_WAIT
          value: "35"

      - name: provisioner
        image: provisioner:version
        imagePullPolicy: Always
        volumeMounts:
        - name: markdown
          mountPath: /src

      volumes:
      - name: markdown
        emptyDir: {}

      - name: secr
        secret:
          secretName: bb
          defaultMode: 256

